### ISSUE TITLE
datafable.com is offline

### ISSUE THREAD

**Issue by mlinksva** [peterdesmet/peterdesmet.github.io#47]
This impacts rendering of http://peterdesmet.com/posts/analyzing-gbif-data-licenses.html

It appears this is very recent https://web.archive.org/web/20230320104459/http://peterdesmet.com/posts/analyzing-gbif-data-licenses.html vs https://web.archive.org/web/20230405182853/http://peterdesmet.com/posts/analyzing-gbif-data-licenses.html

In Chromium-based browsers, the page renders, just with some blank spaces where visualizations were. In Firefox, rendering seems to hang waiting on requests to datafable.com

**Comment by peterdesmet** [comment]
Thanks for reporting. The domain datafable.com was recently discontinued. I've updated the links to datafable.github.io and the charts load again now.
